# Generated by Django 5.1.2 on 2024-11-03 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NenPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enhancer', models.IntegerField()),
                ('Transmutator', models.IntegerField()),
                ('Emitter', models.IntegerField()),
                ('Conjurer', models.IntegerField()),
                ('Manipulator', models.IntegerField()),
                ('Specialist', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
