# Generated by Django 5.1.2 on 2024-11-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nen_type', '0002_nenpoints_answered_fiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nenpoints',
            name='Conjurer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nenpoints',
            name='Emitter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nenpoints',
            name='Enhancer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nenpoints',
            name='Manipulator',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nenpoints',
            name='Specialist',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nenpoints',
            name='Transmutator',
            field=models.IntegerField(default=0),
        ),
    ]
