# Generated by Django 5.1.2 on 2024-11-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nen_type', '0003_alter_nenpoints_conjurer_alter_nenpoints_emitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nenpoints',
            name='Num_answers',
            field=models.IntegerField(default=0),
        ),
    ]
